#!/usr/bin/env Rscript
# Title: "Step 4 - Extract Annotated Splicing Junctions to Analyze"
# September 24, 2025 | Gaurav Raichand | The Insitute of Cancer Research
# Tweaks for Hartwig dataset: Dynamic paths/filenames via config, chr prefix handling, efficient filtering with data.table.
# September 24, 2025 | Gaurav Raichand

###########################################################################
#  Step 0: Load Packages and Data -----------------------------------------
###########################################################################

rm(list = ls(all.names = TRUE))

library(readxl)
library(tidyverse)
library(data.table)

input_dir <- Sys.getenv("INPUT_DIR")
output_dir <- Sys.getenv("OUTPUT_DIR")
setwd(input_dir)

# Load the sj.annot.ref file generated by the STAR-aligner index
filename_sj <- "sjdbList.fromGTF.out.tab"
dataframe_sj <- fread(filename_sj, header = FALSE)
setnames(dataframe_sj, old = 1:4, new = c("chr", "int.start", "int.end", "strand"))

# --- load Step-03 GTF file (lives in results/) ---------------------------
min_tpm   <- as.numeric(Sys.getenv("MIN_TPM", unset = "10"))
filename_gtf <- file.path(Sys.getenv("OUTPUT_DIR"),      # <-- use OUTPUT_DIR
                          sprintf("GTF_ProteinCoding_Filter%s_%s.tsv",
                                  min_tpm,
                                  format(Sys.Date(), "%Y%m%d")))

setwd(Sys.getenv("OUTPUT_DIR"))                          # <-- switch to results/
dataframe_gtf <- fread(filename_gtf)                     # now it’s found
setwd(input_dir)                                         # return to 0_Input_Files

###########################################################################
#  Step 1: Modify the Column Names of the SJ File -------------------------
###########################################################################
# Column names already assigned during loading for efficiency.

###########################################################################
#  Step 2: Filter and Retain Splicing Junctions ---------------------------
###########################################################################

start.time <- proc.time()

# Handle chromosome naming consistency (e.g., if SJ has "chr" but GTF doesn't)
if (all(grepl("^chr", dataframe_sj$chr)) && !any(grepl("^chr", dataframe_gtf$chr))) {
  message("[INFO] Removing 'chr' prefix from SJ for consistency with GTF")
  dataframe_sj[, chr := sub("^chr", "", chr)]
} else if (!all(grepl("^chr", dataframe_sj$chr)) && any(grepl("^chr", dataframe_gtf$chr))) {
  message("[INFO] Adding 'chr' prefix to SJ for consistency with GTF")
  dataframe_sj[, chr := paste0("chr", chr)]
}

# Efficient filtering using data.table non-equi join (replaces slow loop, same logic: SJ within GTF intervals)
filtered_sj <- dataframe_sj[dataframe_gtf, on = .(chr, strand, int.start > start, int.end < end), nomatch = 0,
                            allow.cartesian = TRUE]  # Allow if multiple overlaps

# Generate junction ID and select columns
filtered_sj[, junc.id := paste0("chr", chr, ":", strand, ":", (int.start - 1), "-", int.end)]
dataframe_sj.retain <- filtered_sj[, .(junc.id, chr, strand, int.start, int.end)]

RUNTIME <- proc.time() - start.time
print(RUNTIME)  # sec

# Optional: Table of chromosomes (as in original)
table(dataframe_sj.retain$chr)

###########################################################################
#  Step 3: Output Data ----------------------------------------------------
###########################################################################

setwd(output_dir)

# Dynamic output filename with current date
current_date <- format(Sys.Date(), "%Y%m%d")
filename_output <- paste0("SJ_List_Filtered_by_GTF_ProteinCoding_ExpressedTranscripts_", current_date, ".tsv")
fwrite(dataframe_sj.retain, filename_output, sep = "\t", quote = FALSE, col.names = TRUE)

message("[INFO] Written: ", filename_output)
